# Generated by Django 4.1.5 on 2023-01-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('in_file_loc', models.TextField(primary_key=True, serialize=False, verbose_name='Input File Location')),
                ('out_file_loc', models.TextField(max_length=100, verbose_name='Output File Location')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
            ],
        ),
    ]
