# Generated by Django 4.1.5 on 2023-01-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_file_loc', models.TextField(verbose_name='Input File Location')),
                ('out_file_loc', models.TextField(max_length=100, verbose_name='Output File Location')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.CharField(max_length=300)),
                ('graph_type', models.CharField(max_length=20)),
                ('feature_type', models.CharField(max_length=20)),
                ('test_size', models.DecimalField(decimal_places=2, max_digits=2)),
                ('n_jobs', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
