# Generated by Django 4.1.5 on 2023-01-21 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0002_order_parameter_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='out_file_loc',
        ),
        migrations.AddField(
            model_name='order',
            name='feature_type',
            field=models.CharField(default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('f8523645-8b7b-41d6-89d8-c90090a09fa2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='graph_type',
            field=models.CharField(default='directed', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='n_jobs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='test_size',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='in_file_loc',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='ready', max_length=50),
        ),
    ]
