# Generated by Django 4.1.5 on 2023-01-23 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0003_remove_order_id_remove_order_out_file_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('69df8364-c795-401a-b094-d9954e6b34fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
