# Generated by Django 4.1.5 on 2023-01-23 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0004_alter_order_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ad7cf90a-1922-4a54-b797-bb99b9b0f47f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
