# Generated by Django 4.1.5 on 2023-03-05 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0005_alter_order_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('76cf6f41-c829-406a-a64e-4fd4a120c581'), editable=False, primary_key=True, serialize=False),
        ),
    ]
