# Generated by Django 4.1.5 on 2023-03-05 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0006_alter_order_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c7581a2b-d36d-4233-aaff-2ccaff980f0c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
