# Generated by Django 4.1.5 on 2023-03-06 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0007_alter_order_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('35945162-9f81-4d57-bdfa-73847680c727'), editable=False, primary_key=True, serialize=False),
        ),
    ]
