# Generated by Django 4.1.5 on 2023-03-06 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0010_alter_order_file_id_alter_order_out_file_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('5b9184e8-b197-41e3-9354-705ac7432c24'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='out_file_loc',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
