# Generated by Django 4.1.5 on 2023-03-06 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0011_alter_order_file_id_alter_order_out_file_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='out_file_loc',
        ),
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6361681b-225b-440f-aa31-78ceb801bfc5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
