# Generated by Django 4.1.5 on 2023-03-06 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0012_remove_order_out_file_loc_alter_order_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9bbdd59b-f1d4-46b9-b99e-35738483500d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
