# Generated by Django 4.1.5 on 2023-03-06 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0014_order_out_file_loc_alter_order_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c00643f2-a6b6-404c-97a8-cd37d1d84b23'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='out_file_loc',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
